name = "messenlead"
compatibility_date = "2026-04-24"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "messenlead-db"
database_id = "ab405875-90ab-4484-aa12-663940ba6524"
